swagger: "2.0"
info:
  description: |
    This is a sample Coupons microservice API.

    [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.

  version: "1.0.0"
  title: Swagger Coupons
  termsOfService: http://osoco.es/terms/
  contact:
    name: apiteam@osoco.es
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: coupons.osoco.es
basePath: /v1
schemes:
  - http
paths:
  /coupons:
    post:
      tags:
        - coupon
      summary: Add a new coupon
      description: ""
      operationId: addCoupon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Coupon object that needs to be added
          required: false
          schema:
            $ref: "#/definitions/Coupon"
      responses:
        "405":
          description: Invalid input
      security:
        - coupons_auth:
          - write_coupons
          - read_coupons
    put:
      tags:
        - coupon
      summary: Update an existing coupon
      description: ""
      operationId: updateCoupon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Coupon object that needs to be added
          required: false
          schema:
            $ref: "#/definitions/Coupon"
      responses:
        "405":
          description: Validation exception
        "404":
          description: Coupon not found
        "400":
          description: Invalid CODE supplied
      security:
        - coupons_auth:
          - write_coupons
          - read_coupons
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  coupons_auth:
    type: oauth2
    authorizationUrl: http://coupons.osoco.es/api/oauth/dialog
    flow: implicit
    scopes:
      write_coupons: modify coupons
      read_coupons: read coupons
definitions:
  Coupon:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      description:
        type: string
      numMaxUsage:
        type: integer
        format: int32
      expirationDate:
        type: string
      discount:
        type: integer