swagger: "2.0"
info:
  description: |
    This is a sample Coupons microservice API.

    [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.

  version: "1.0.0"
  title: Swagger Coupons
  termsOfService: http://osoco.es/terms/
  contact:
    name: apiteam@osoco.es
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: coupons.osoco.es
basePath: /v1
schemes:
  - http
paths:
  /coupons:
    post:
      tags:
        - coupon
      summary: Add a new coupon
      description: ""
      operationId: addCoupon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Coupon object that needs to be added
          required: false
          schema:
            $ref: "#/definitions/Coupon"
      responses:
        "405":
          description: Invalid input

    put:
      tags:
        - coupon
      summary: Update an existing coupon
      description: ""
      operationId: updateCoupon
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Coupon object that needs to be added
          required: false
          schema:
            $ref: "#/definitions/Coupon"
      responses:
        "405":
          description: Validation exception
        "404":
          description: Coupon not found
        "400":
          description: Invalid CODE supplied

    get:
      tags:
        - coupon
      summary: Finds coupons
      description: Returns all coupons.
      operationId: getAllCoupons
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Coupon"

  /coupons/{code}:
    get:
      tags:
        - coupon
      summary: Find coupon by code
      description: Returns a coupon with CODE = code
      operationId: getCouponByCode
      produces:
        - application/json
      parameters:
        - in: path
          name: code
          description: Code of coupon that needs to be fetched
          required: true
          type: string
      responses:
        "404":
          description: Coupon not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Coupon"
        "400":
          description: Invalid coupon supplied

    delete:
      tags:
        - coupon
      summary: Deletes a coupon
      description: ""
      operationId: deleteCoupon
      produces:
        - application/json
      parameters:
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        - in: path
          name: code
          description: Code to delete
          required: true
          type: string
      responses:
        "400":
          description: Invalid coupon code value
          
  /coupons/{code}/validations:
    post:
      tags:
        - coupon
        - validation
      summary: Attempt to validate a coupon and get the discount that it grants.
      description: This does not consume the coupon.
      operationId: validateCoupon
      produces:
        - application/json
      parameters:
        - in: path
          name: code
          description: the coupon code
          required: true
          type: string
      responses:
        "201":
          schema:
            $ref: "#/definitions/ValidationResult"
          description: The coupon is valid and grants a discount
        "204":
          description: The coupon exists, but does not grant a discount
        "404":
          description: Coupon not found
          
  /coupons/{code}/redemptions:
    post:
      tags:
        - coupon
        - redemption
      summary: Attempt to redeem a coupon.
      description: This consumes one use of the coupon.
      operationId: redeemCoupon
      produces:
        - application/json
      parameters:
        - in: path
          name: code
          description: the coupon code
          required: true
          type: string
      responses:
        "201":
          description: The coupon is valid and grants a discount
        "404":
          description: Coupon not found


securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
      
definitions:

  Coupon:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      description:
        type: string
      numMaxUsage:
        type: integer
        format: int32
      expirationDate:
        type: string
      discount:
        type: integer
        
  ValidationResult:
    type: object
    required:
      - discount
    properties:
      discount:
        type: integer
        format: int32
        description: The discount granted by the coupon, as a percent. For example, 45 would be 45%
        example: 15